// Preserved dynamic presentation patterns from macos/web/index.html.
export function uiPatterns(localizedText:(s:string)=>string,localizedSystemText:(s:string,fallback?:string)=>string):[RegExp,(...captures:string[])=>string][]{
 return [
  [/^显示 (\d+) \/ (\d+)$/,(_,shown,total)=>`Showing ${shown} of ${total}`],[/^已选 (\d+)$/,(_,count)=>`${count} selected`],[/^NFO (\d+) 个$/,(_,count)=>`${count} NFOs`],[/^当前选择 (\d+) 项$/,(_,count)=>`${count} selected items`],[/^(\d+) 集$/,(_,count)=>`${count} episodes`],[/^第 (.+) 季$/,(_,season)=>`Season ${season}`],[/^拖拽调整 (.+) 列宽$/,(_,label)=>`Drag to resize the ${localizedText(label)} column`],
  [/^共 (\d+) · 可生成 (\d+) · AI 完成 (\d+) · 缺 Spec (\d+)(?: · 有问题 (\d+))?$/,(_,total,ready,ai,nospec,error)=>`Total ${total} · Ready ${ready} · AI complete ${ai} · Missing Specs ${nospec}${error?` · Issues ${error}`:''}`],
  [/^指定为 (.+)$/,(_,status)=>`Set to ${localizedText(status)}`],[/^(\d+) 条 · (会生成 Tag|仅保存 Spec)$/,(_,count,kind)=>`${count} ${count==='1'?'value':'values'} · ${localizedText(kind)}`],[/^黄色：(AI|规则)生成标签　·　蓝灰：NFO 现有标签$/,(_,engine)=>`Yellow: ${engine==='AI'?'AI':'Rules'} generated tags · Blue-gray: existing NFO tags`],[/^警告：(.+)$/,(_,message)=>`Warning: ${message}`],[/^复核说明：(.+)$/,(_,message)=>`Review Notes: ${message}`],
  [/^人工规格 · 可生成$/,()=>`Manual Specs · Ready to Generate`],[/^(.+) ·手动$/,(_,status)=>`${localizedText(status)} · Manual`],[/^已忽略 (\d+) 项；文件与身份仍显示权威的一致性结果，NFO 内容变化后会自动重新检查。$/,(_,count)=>`${count} ignored; authoritative file and identity consistency remains visible. Checks resume when the NFO changes.`],[/^IMDb 原始抓取值：(.*)$/,(_,value)=>`Original IMDb Value: ${value}`],
  [/^(正在预检)( AI|规则)范围…$/,(_,verb,engine)=>`Checking the ${engine.trim()==='AI'?'AI':'Rules'} scope…`],[/^已提交(AI|规则)生成任务$/,(_,engine)=>`${engine==='AI'?'AI':'Rules'} generation task submitted`],[/^(AI|规则)试写一次最多 (\d+) 个 NFO$/,(_,engine,count)=>`${engine==='AI'?'AI':'Rules'} preview is limited to ${count} NFOs at a time.`],[/^正在预检(AI|规则)范围$/,(_,engine)=>`Checking the ${engine==='AI'?'AI':'Rules'} scope`],[/^已提交(AI|规则)试写（完成后自动弹出审核面板）$/,(_,engine)=>`${engine==='AI'?'AI':'Rules'} preview submitted; the review panel will open when it completes.`],
  [/^(AI|规则)生成标签\n范围：(.+)\n总数：(\d+)\n预计需生成：(\d+)\n\n只有校验成功后才会替换软件拥有的旧 Generated Tag。$/,(_,engine,scope,total,needed)=>`${engine==='AI'?'AI':'Rules'} Tag Generation\nScope: ${localizedText(scope)}\nTotal: ${total}\nExpected to generate: ${needed}\n\nOnly validated replacements can replace old Generated Tags owned by this app.`],[/^只更新 Technical Specs，不生成标签。\n范围：(.+)\n共 (\d+) 个 NFO，继续？$/,(_,scope,total)=>`Update Technical Specs only, without generating tags.\nScope: ${localizedText(scope)}\n${total} NFOs. Continue?`],
  [/^该标签来自外部应用（如 TMM）：\n([\s\S]+)\n\n删除仅移除这一个根节点 <tag>，可通过“撤销”恢复。确认删除？$/,(_,tag)=>`This tag belongs to an external app such as TMM:\n${tag}\n\nOnly this root <tag> node will be removed. Undo is available. Delete it?`],[/^删除标签“([\s\S]+)”？\n（可用“撤销”恢复）$/,(_,tag)=>`Delete tag “${tag}”?\n(Undo is available.)`],[/^新增 (.+) 规格值$/,(_,name)=>`Add ${name} Spec value`],[/^编辑 (.+)$/,(_,name)=>`Edit ${name}`],[/^即将删除以下 (\d+) 个 AI 生成标签：\n\n([\s\S]+)\n\n确认删除？（可撤销）$/,(_,count,tags)=>`The following ${count} AI-generated tags will be deleted:\n\n${tags}\n\nDelete them? (Undo is available.)`],[/^将标签“([\s\S]+)”的所有权改为 (.+)？\n（写入 NFO ownership 清单，可撤销）$/,(_,tag,owner)=>`Change ownership of “${tag}” to ${localizedText(owner)}?\n(The NFO ownership manifest will be updated; Undo is available.)`],
  [/^采纳并写入 (\d+) 个 NFO 的(AI|规则)试写结果？\n写入前会再次校验 NFO 是否发生变化。$/,(_,count,engine)=>`Approve and write ${engine==='AI'?'AI':'Rules'} preview results for ${count} NFOs?\nEach NFO will be revalidated before writing.`],[/^(.+)：可访问$/,(_,path)=>`${path}: Accessible`],[/^(.+)：不可访问$/,(_,path)=>`${path}: Inaccessible`],[/^正在扫描(电影|电视剧)媒体库…$/,(_,space)=>`Scanning the ${space==='电影'?'movie':'TV'} library…`],
  [/^(\d+) 个 NFO · 使用已缓存模型结果，不再次请求 AI$/,(_,count)=>`${count} NFOs · Uses cached model results without another AI request`],[/^(\d+) 个 NFO · 采纳后直接写入已审核的规则结果$/,(_,count)=>`${count} NFOs · Approval writes the reviewed Rules result directly`],[/^原始页面 (\d+) · 解析结果 (\d+)$/,(_,raw,parsed)=>`Raw Pages ${raw} · Parsed Results ${parsed}`],[/^（建议：(电视剧|电影|待分类) · (在线|离线)）$/,(_,space,online)=>`(Suggested: ${localizedText(space)} · ${localizedText(online)})`],
  [/^(已整理|等待整理|正在整理|整理失败|部分缓存正在使用|仍超出上限|尚未完成统计) · (.+) · 原始页面 (\d+) · 解析结果 (\d+)$/,(_,status,usage,raw,parsed)=>`${localizedText(status)} · ${usage} · Raw Pages ${raw} · Parsed Results ${parsed}`],[/^↻ 重新读取（(\d+) 个）$/,(_,count)=>`↻ Reload (${count})`],[/^👁 AI 预演（≤(\d+)）$/,(_,count)=>`👁 AI Preview (≤${count})`],
  [/^AI Runtime：(.+)$/,(_,status)=>`AI Runtime: ${localizedText(status)}`],[/^跳过：(.+)$/,(_,title)=>`Skipped: ${title}`],[/^采纳任务有失败项：(.+)；已同步成功写入的 NFO$/,(_,message)=>`Some approvals failed: ${localizedSystemText(message)} Successfully written NFOs were synchronized.`],[/^已重新读取 (\d+) 个 NFO；(\d+) 个因筛选或排序结果变化已更新位置$/,(_,count,hidden)=>`Reloaded ${count} NFOs; ${hidden} moved because filters or sorting changed.`],[/^(.+) · 进度 (\d+)\/(\d+)(.*)$/,(_,action,done,total,current)=>`${localizedText(action)} · Progress ${done}/${total}${current}`],
  [/^已选 (\d+) 个 · 点击列表中的任意一行查看其详情（不影响选择）$/,(_,count)=>`${count} selected · Select any row to inspect it without changing the selection.`],[/^（已选 (\d+) 个，点击其他行可继续查看）$/,(_,count)=>`(${count} selected; select another row to inspect it)`],
  [/^正在重新读取 (\d+) 个 NFO…$/,(_,count)=>`Reloading ${count} NFOs…`],[/^已重新读取 (\d+) 个 NFO，列表与预览已同步$/,(_,count)=>`Reloaded ${count} NFOs; the list and preview are synchronized.`],[/^最新版本 (.+) 可用$/,(_,version)=>`Version ${version} is available`],[/^已是最新版本 (.+)$/,(_,version)=>`Up to date (${version})`],[/^检查失败：(.+)$/,(_,message)=>`Update check failed: ${message}`],
  [/^📦 资料库对账完成：共 (\d+) 个 NFO，复用 (\d+)，重新解析 (\d+)。$/,(_,total,reused,reparsed)=>`📦 Library reconciliation complete: ${total} NFOs, ${reused} reused, ${reparsed} reparsed.`],[/^✅ \[(\d+)\/(\d+)\] (AI|规则) Tag 已写入：(.+)$/,(_,index,total,engine,title)=>`✅ [${index}/${total}] ${engine==='AI'?'AI':'Rules'} tags written: ${title}`],[/^🟡 \[(\d+)\/(\d+)\] AI 结果需复核，NFO 未改：(.+)$/,(_,index,total,title)=>`🟡 [${index}/${total}] AI result needs review; NFO unchanged: ${title}`],[/^❌ \[(\d+)\/(\d+)\] NFO 读取失败：(.+)$/,(_,index,total,error)=>`❌ [${index}/${total}] Failed to read NFO: ${localizedSystemText(error)}`],[/^⏭️ \[(\d+)\/(\d+)\] 已知 AI 失败未变化，跳过请求：(.+)$/,(_,index,total,title)=>`⏭️ [${index}/${total}] Known AI failure is unchanged; request skipped: ${title}`],[/^⏸️ AI 批量任务已暂停；(.+)$/,(_,detail)=>`⏸️ AI batch task paused; ${localizedSystemText(detail,'resume it from Task Center when ready.')}`],[/^⏸️ AI Runtime 已(?:按预算)?暂停：(.+)$/,(_,reason)=>`⏸️ AI Runtime paused: ${localizedSystemText(reason)}`],[/^📊 (.+)$/,(_,metrics)=>`📊 Progress metrics: ${metrics}`],[/^完成：\s*(.+)$/,(_,summary)=>`Completed: ${summary.replaceAll('，',', ')}`],[/^本任务新增模型 Usage：(.+)$/,(_,usage)=>`New model usage for this task: ${usage}`],[/^缓存命中结果历史 Usage（本次不重复扣费）：(.+)$/,(_,usage)=>`Historical usage for cache hits (not charged again): ${usage}`],[/^当前持久化 AI 失败队列：(\d+) 项$/,(_,count)=>`Persistent AI failure queue: ${count} items`],[/^✅ (AI|规则)?预演完成：(.+)（(\d+) 个候选标签）$/,(_,engine,title,count)=>`✅ ${engine==='AI'?'AI':'Rules'} preview complete: ${title} (${count} candidate tags)`],[/^(AI|规则)?预演结果已保存：(\d+) 成功，(\d+) 跳过。?(.*)$/,(_,engine,success,skipped,note)=>`${engine==='AI'?'AI':'Rules'} preview results saved: ${success} succeeded, ${skipped} skipped.${note?' Review and approve them in the preview panel.':''}`],[/^规则试写采纳完成：(\d+) 成功，(\d+) 失败。?$/,(_,success,failed)=>`Rules preview approval complete: ${success} succeeded, ${failed} failed.`]
];
}
